Lecture 1 starts with a matrix K


% Create the matrix used in the lecture
K_matrix = [[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]]

% Or create K_matrix using the toeplitz command
import scipy.linalg
scipy.linalg.toeplitz([2,-1,0,0])

% Properties of the matrix K



%
import numpy
K_matrix == numpy.transpose(K_matrix)


In [ ]:
% Create the matrix used in the lecture
K_matrix = [[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]]

In [2]:
# Or create K_matrix using the toeplitz command
import scipy.linalg
K_matrix = scipy.linalg.toeplitz([2,-1,0,0])
print(K_matrix)

[[ 2 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  2]]


### Exploring the Properties of K

#### Symmetry

$K$ is *symmetric* iff $ K = K^{T} $

In [7]:
# numpy is the package with the "transpose" command
import numpy

# If K is symmetric, then K = K^T
K_matrix == numpy.transpose(K_matrix)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

#### Sparse

A sparse matrix consists of mostly zeroes. It that allows special [computational] techniques to take advantage of the large number of "background" (commonly zero) elements.  The number of zeros a matrix needs in order to be considered "sparse" depends on the structure of the matrix and the desired operations to perform on it.<sup>1</sup>

1. Davis, Tim and Weisstein, Eric W. "Sparse Matrix." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/SparseMatrix.html

In [8]:
# count_nonzero is the numpy command for counting the non-zero elements of a sparse matrix
numpy.count_nonzero(K_matrix)

10

#### Tridiagonal

A square matrix with nonzero elements only on the diagonal and slots horizontally or vertically adjacent the diagonal.<sup>1</sup>.

1. Weisstein, Eric W. "Tridiagonal Matrix." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/TridiagonalMatrix.html


#### Constant diagonal

$K_{i,i} = K_{j,j}$ for natural numbers $i,j$ up to $4$. For example, $K_{1,1} = K_{2,2} = 2$ and so on.  Furthermore, the matrix $K$ it is constant on each and every diagonal.

#### Periodic

#### Invertible

There exists a matrix $K^{-1}$ such that $KK^{-1} = K^{-1}K = I$

In [12]:
# numpy command for the identity matrix is eye(N)
print(numpy.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


We can show a matrix is invertible by row-reducing.