Lecture 1 starts with a matrix K


% Create the matrix used in the lecture
K_matrix = [[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]]

% Or create K_matrix using the toeplitz command
import scipy.linalg
scipy.linalg.toeplitz([2,-1,0,0])

% Properties of the matrix K



%
import numpy
K_matrix == numpy.transpose(K_matrix)


In [4]:
# Create the matrix used in the lecture
K_matrix = [[2,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]]

In [5]:
# Or create K_matrix using the toeplitz command
import scipy.linalg
K_matrix = scipy.linalg.toeplitz([2,-1,0,0])
print(K_matrix)

[[ 2 -1  0  0]
 [-1  2 -1  0]
 [ 0 -1  2 -1]
 [ 0  0 -1  2]]


### Exploring the Properties of K

#### Symmetry

$K$ is *symmetric* iff $ K = K^{T} $

In [6]:
# numpy is the package with the "transpose" command
import numpy

# If K is symmetric, then K = K^T
K_matrix == numpy.transpose(K_matrix)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

#### Sparse

A sparse matrix consists of mostly zeroes. It that allows special [computational] techniques to take advantage of the large number of "background" (commonly zero) elements.  The number of zeros a matrix needs in order to be considered "sparse" depends on the structure of the matrix and the desired operations to perform on it.<sup>1</sup>

1. Davis, Tim and Weisstein, Eric W. "Sparse Matrix." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/SparseMatrix.html

In [7]:
# count_nonzero is the numpy command for counting the non-zero elements of a sparse matrix
numpy.count_nonzero(K_matrix)

10

#### Tridiagonal

A square matrix with nonzero elements only on the diagonal and slots horizontally or vertically adjacent the diagonal.<sup>1</sup>.

1. Weisstein, Eric W. "Tridiagonal Matrix." From MathWorld--A Wolfram Web Resource. http://mathworld.wolfram.com/TridiagonalMatrix.html


#### Constant diagonal

$K_{i,i} = K_{j,j}$ for natural numbers $i,j$ up to $4$. For example, $K_{1,1} = K_{2,2} = 2$ and so on.  Furthermore, the matrix $K$ it is constant on each and every diagonal.

#### Invertible

There exists a matrix $K^{-1}$ such that $KK^{-1} = K^{-1}K = I$

In [8]:
# numpy command for the identity matrix is eye(N)
print(numpy.eye(4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


We can show a matrix is invertible by row-reducing.

In [9]:
# Create the inverse matrix 
K_inv_matrix = [[2,0,0,0],[0,3/2,0,0],[0,0,4/3,0],[0,0,0,5/4]]

# show the product is the Identity matrix
K_inv_matrix * K_matrix

array([[ 4.        , -0.        ,  0.        ,  0.        ],
       [-0.        ,  3.        , -0.        ,  0.        ],
       [ 0.        , -0.        ,  2.66666667, -0.        ],
       [ 0.        ,  0.        , -0.        ,  2.5       ]])

#### What happens if we change K a little bit?

In [21]:
# Create the matrix used in the lecture
C_matrix = [[2,-1,0,-1],[-1,2,-1,0],[0,-1,2,-1],[-1,0,-1,2]]
print(C_matrix)

[[2, -1, 0, -1], [-1, 2, -1, 0], [0, -1, 2, -1], [-1, 0, -1, 2]]


C is the circulant matrix. It is not invertible. We can show this by finding a vector that maps to the null space.
We want to find a vector, $u$, such that $C u = 0$. This is a proof by contradiction. If $C$ is invertible, then $C^{-1} C u = C^{-1} * 0 = 0$. Thus $u = 0$, which is a contradiction.

In [25]:
u_matrix = [[1],[1],[1],[1]]
numpy.matmul(C_matrix, u_matrix)

array([[0],
       [0],
       [0],
       [0]])

K is a fixed-fixed matrix. 
C is a circulant matrix.
We also want to look at T, a free-fixed matrix, and B, a free-free matrix.

In [27]:
T_matrix = [[1,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,2]]
print(T_matrix)

[[1, -1, 0, 0], [-1, 2, -1, 0], [0, -1, 2, -1], [0, 0, -1, 2]]


In [28]:
B_matrix = [[1,-1,0,0],[-1,2,-1,0],[0,-1,2,-1],[0,0,-1,1]]
print(B_matrix)

[[1, -1, 0, 0], [-1, 2, -1, 0], [0, -1, 2, -1], [0, 0, -1, 1]]
